### ISSUE TITLE
Port 3D MBD model (vehicle) to C++

### ISSUE THREAD

**Issue by DrStS** [DrStS/EVAA#6]

**Comment by khatrishubham88** [comment]
@teo2605 @le-raffael @S14P  Do you think using closure would be a good idea instead of a class for compute_f  function, we can use it in the way we did in the matlab function. Following is an article on closure:
https://www.cprogramming.com/c++11/c++11-lambda-closures.html
https://en.cppreference.com/w/cpp/language/lambda

**Comment by khatrishubham88** [comment]
Implemented MBD_method.h [# 5063375](https://github.com/DrStS/EVAA/commit/506337547e8e9537b8bb0a974b01834e29dac1d3)
